//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USRv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTableProperties
    {
        public int MainTablePropertieId { get; set; }
        public float SclMax { get; set; }
        public float SclMin { get; set; }
        public bool IsCutOffMax { get; set; }
        public float CutOffMax { get; set; }
        public bool IsCutOffMin { get; set; }
        public float CutOffMin { get; set; }
    
        public virtual MainTables MainTables { get; set; }
    }
}
