//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USRv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumericSamples
    {
        public int TagId { get; set; }
        public System.DateTime SampleDateTime { get; set; }
        public float SampleValue { get; set; }
        public int QualityId { get; set; }
    
        public virtual MainTables MainTables { get; set; }
        public virtual Qualities Qualities { get; set; }
    }
}
