// <auto-generated />
namespace USRv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addapitesr23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addapitesr23));
        
        string IMigrationMetadata.Id
        {
            get { return "201802270752026_add-api-tesr23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
