// <auto-generated />
namespace USRv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addapitesr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addapitesr));
        
        string IMigrationMetadata.Id
        {
            get { return "201802270609393_add-api-tesr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
